-- Studcha / Chat: anonymous rooms, no login required.
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{8}$'),
  name text not null check (char_length(trim(name)) between 1 and 60),
  created_at timestamptz not null default now()
);

create table if not exists public.room_members (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  guest_id uuid not null,
  display_name text not null check (char_length(trim(display_name)) between 1 and 30),
  joined_at timestamptz not null default now(),
  unique(room_id, guest_id)
);

create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  guest_id uuid not null,
  display_name text not null check (char_length(trim(display_name)) between 1 and 30),
  body text not null check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists rooms_code_idx on public.rooms(code);
create index if not exists room_members_room_idx on public.room_members(room_id, joined_at);
create index if not exists room_messages_room_idx on public.room_messages(room_id, created_at);

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.room_messages enable row level security;

-- Public anonymous access. Room codes are random and 8 characters long.
drop policy if exists rooms_select_anon on public.rooms;
create policy rooms_select_anon on public.rooms for select to anon, authenticated using (true);

drop policy if exists members_select_anon on public.room_members;
create policy members_select_anon on public.room_members for select to anon, authenticated using (true);

drop policy if exists members_insert_anon on public.room_members;
create policy members_insert_anon on public.room_members for insert to anon, authenticated with check (guest_id is not null);

drop policy if exists members_delete_anon on public.room_members;
create policy members_delete_anon on public.room_members for delete to anon, authenticated using (guest_id is not null);

drop policy if exists messages_select_anon on public.room_messages;
create policy messages_select_anon on public.room_messages for select to anon, authenticated using (true);

drop policy if exists messages_insert_anon on public.room_messages;
create policy messages_insert_anon on public.room_messages for insert to anon, authenticated with check (guest_id is not null);

create or replace function public.make_room_code()
returns text
language plpgsql
as $$
declare
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i integer;
begin
  for i in 1..8 loop
    result := result || substr(chars, 1 + floor(random() * length(chars))::int, 1);
  end loop;
  return result;
end;
$$;

create or replace function public.create_room(room_name text, p_guest_id uuid, p_display_name text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.rooms;
  c text;
begin
  if p_guest_id is null then raise exception 'Guest id required'; end if;
  if char_length(trim(coalesce(room_name,''))) not between 1 and 60 then raise exception 'Invalid room name'; end if;
  if char_length(trim(coalesce(p_display_name,''))) not between 1 and 30 then raise exception 'Invalid display name'; end if;

  loop
    c := public.make_room_code();
    begin
      insert into public.rooms(code,name) values(c,trim(room_name)) returning * into r;
      exit;
    exception when unique_violation then
      null;
    end;
  end loop;

  insert into public.room_members(room_id,guest_id,display_name)
  values(r.id,p_guest_id,trim(p_display_name))
  on conflict (room_id,guest_id) do update set display_name=excluded.display_name;

  return r;
end;
$$;

grant execute on function public.create_room(text, uuid, text) to anon, authenticated;

create or replace function public.join_room(room_code text, p_guest_id uuid, p_display_name text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.rooms;
begin
  if p_guest_id is null then raise exception 'Guest id required'; end if;
  if char_length(trim(coalesce(p_display_name,''))) not between 1 and 30 then raise exception 'Invalid display name'; end if;

  select * into r from public.rooms where code = upper(trim(room_code));
  if not found then raise exception 'Room not found'; end if;

  insert into public.room_members(room_id,guest_id,display_name)
  values(r.id,p_guest_id,trim(p_display_name))
  on conflict (room_id,guest_id) do update set display_name=excluded.display_name;

  return r;
end;
$$;

grant execute on function public.join_room(text, uuid, text) to anon, authenticated;

do $$ begin
  alter publication supabase_realtime add table public.room_members;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.room_messages;
exception when duplicate_object then null; end $$;
