-- CHAT ROOMS: run this after supabase-schema.sql
create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{6,12}$'),
  name text not null check (char_length(name) between 1 and 60),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.room_members (
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(room_id,user_id)
);
create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists room_members_user_idx on public.room_members(user_id);
create index if not exists room_messages_room_idx on public.room_messages(room_id,created_at);

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.room_messages enable row level security;

drop policy if exists rooms_select_member on public.rooms;
create policy rooms_select_member on public.rooms for select to authenticated using (exists(select 1 from public.room_members m where m.room_id=id and m.user_id=auth.uid()));
drop policy if exists rooms_insert_owner on public.rooms;
create policy rooms_insert_owner on public.rooms for insert to authenticated with check (owner_id=auth.uid());

drop policy if exists room_members_select_member on public.room_members;
create policy room_members_select_member on public.room_members for select to authenticated using (exists(select 1 from public.room_members me where me.room_id=room_id and me.user_id=auth.uid()));
drop policy if exists room_members_insert_self on public.room_members;
create policy room_members_insert_self on public.room_members for insert to authenticated with check (user_id=auth.uid());

drop policy if exists room_messages_select_member on public.room_messages;
create policy room_messages_select_member on public.room_messages for select to authenticated using (exists(select 1 from public.room_members m where m.room_id=room_messages.room_id and m.user_id=auth.uid()));
drop policy if exists room_messages_insert_member on public.room_messages;
create policy room_messages_insert_member on public.room_messages for insert to authenticated with check (sender_id=auth.uid() and exists(select 1 from public.room_members m where m.room_id=room_messages.room_id and m.user_id=auth.uid()));

drop function if exists public.create_room(text);
create or replace function public.create_room(room_name text)
returns public.rooms
language plpgsql security definer set search_path=public as $$
declare r public.rooms; c text;
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if;
 c := upper(substr(encode(gen_random_bytes(8),'hex'),1,8));
 insert into public.rooms(code,name,owner_id) values(c,trim(room_name),auth.uid()) returning * into r;
 insert into public.room_members(room_id,user_id) values(r.id,auth.uid());
 return r;
end; $$;
grant execute on function public.create_room(text) to authenticated;

drop function if exists public.join_room(text);
create or replace function public.join_room(room_code text)
returns public.rooms
language plpgsql security definer set search_path=public as $$
declare r public.rooms;
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if;
 select * into r from public.rooms where code=upper(trim(room_code));
 if not found then raise exception 'Room not found'; end if;
 insert into public.room_members(room_id,user_id) values(r.id,auth.uid()) on conflict do nothing;
 return r;
end; $$;
grant execute on function public.join_room(text) to authenticated;

do $$ begin
 alter publication supabase_realtime add table public.room_messages;
exception when duplicate_object then null;
end $$;
