const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];

let client=null,me=null,myProfile=null,conversations=[],activeConversation=null;
let messageChannel=null,personalCallChannel=null,callChannel=null,pc=null,localStream=null,currentCall=null,pendingIncoming=null;
let isMuted=false,cameraOff=false;
const dark=localStorage.getItem('chat-dark')==='1';
const ICE_SERVERS={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
const cfg=()=>({url:localStorage.getItem('chat-supabase-url')||'',key:localStorage.getItem('chat-supabase-key')||''});
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
const setAuthMessage=(m,ok=false)=>{$('#authMessage').textContent=m||'';$('#authMessage').style.color=ok?'var(--success)':'var(--danger)'};
const initials=n=>(n||'?').trim().slice(0,1).toUpperCase();
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const formatTime=v=>new Intl.DateTimeFormat('ar',{hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const dateLabel=v=>new Intl.DateTimeFormat('ar',{year:'numeric',month:'long',day:'numeric'}).format(new Date(v));
const shareLink=u=>`${location.origin}${location.pathname}?user=${encodeURIComponent(u)}`;
const setAvatar=(e,n)=>e.textContent=initials(n);
const showScreen=n=>['setupScreen','authScreen','app'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==n));

async function boot(){
 document.body.classList.toggle('dark',dark);
 const c=cfg(); if(!c.url||!c.key){showScreen('setupScreen');return;}
 try{client=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session}}=await client.auth.getSession();if(session)await startApp(session.user);else showScreen('authScreen');client.auth.onAuthStateChange(async(_e,s)=>{if(s&&!me)await startApp(s.user);if(!s){me=null;myProfile=null;conversations=[];showScreen('authScreen')}})}catch(e){showScreen('setupScreen');toast('تعذر تشغيل Supabase');console.error(e)}
}

async function startApp(user){
 me=user;const {data,error}=await client.from('profiles').select('*').eq('id',user.id).maybeSingle();
 if(error){setAuthMessage(error.message);return} if(!data){setAuthMessage('لم يتم إنشاء ملف المستخدم. شغّل supabase-schema.sql أولاً.');return}
 myProfile=data;showScreen('app');renderMe();$('#myShareLink').textContent=shareLink(myProfile.username);await loadConversations();await subscribePersonalCalls();handleIncomingProfileLink();
}
function renderMe(){const n=myProfile?.display_name||me.email?.split('@')[0]||'مستخدم';$('#myName').textContent=n;$('#myUsername').textContent='@'+(myProfile?.username||'user');setAvatar($('#myAvatar'),n)}

async function loadConversations(){
 const {data:members,error}=await client.from('conversation_members').select('conversation_id').eq('user_id',me.id);if(error){toast(error.message);return}
 const ids=[...(members||[]).map(x=>x.conversation_id)];if(!ids.length){conversations=[];renderConversationList();renderWelcome();return}
 const [{data:others},{data:messages}]=await Promise.all([client.from('conversation_members').select('conversation_id,user_id,profiles(id,username,display_name)').in('conversation_id',ids).neq('user_id',me.id),client.from('messages').select('id,conversation_id,sender_id,body,attachment_path,attachment_type,created_at').in('conversation_id',ids).order('created_at',{ascending:false})]);
 const byId=new Map(),lastById=new Map();(others||[]).forEach(r=>byId.set(r.conversation_id,r.profiles));(messages||[]).forEach(m=>{if(!lastById.has(m.conversation_id))lastById.set(m.conversation_id,m)});
 conversations=ids.map(id=>({id,other:byId.get(id),last:lastById.get(id)||null})).filter(x=>x.other);renderConversationList();
}
function renderConversationList(filter=''){
 const list=$('#chatList');list.innerHTML='';const n=filter.trim().toLowerCase();const shown=conversations.filter(c=>`${c.other.display_name} ${c.other.username}`.toLowerCase().includes(n));
 if(!shown.length){list.innerHTML='<div class="empty-list">لا توجد محادثات بعد.</div>';return}
 shown.forEach(c=>{const b=document.createElement('button');b.className='chat-item'+(activeConversation?.id===c.id?' active':'');b.innerHTML=`<div class="avatar">${esc(initials(c.other.display_name))}</div><div class="chat-copy"><div class="chat-top"><span class="chat-name">${esc(c.other.display_name)}</span><span class="chat-time">${c.last?formatTime(c.last.created_at):''}</span></div><div class="last-msg">${c.last?(c.last.attachment_path?'📎 ملف':esc(c.last.body||'صورة')):'ابدأ المحادثة'}</div></div>`;b.onclick=()=>openConversation(c);list.appendChild(b)});
}
function renderWelcome(){$('#messages').innerHTML='<div class="welcome"><div>💬</div><h3>مرحبًا بك في Chat</h3><p>ابحث عن زميلك باسم المستخدم أو شارك رابط حسابك لبدء محادثة حقيقية.</p></div>'}

async function openConversation(c){activeConversation=c;renderConversationList($('#chatSearch').value);$('#activeName').textContent=c.other.display_name;$('#activeStatus').textContent='@'+c.other.username;$('#detailsName').textContent=c.other.display_name;$('#detailsUsername').textContent='@'+c.other.username;setAvatar($('#activeAvatar'),c.other.display_name);setAvatar($('#detailsAvatar'),c.other.display_name);$('#sidebar').classList.remove('open');await subscribeMessages(c.id);await loadMessages(c.id)}
async function loadMessages(id){const {data,error}=await client.from('messages').select('id,conversation_id,sender_id,body,attachment_path,attachment_type,created_at').eq('conversation_id',id).order('created_at',{ascending:true});if(error){toast(error.message);return}const box=$('#messages');box.innerHTML='';if(!data?.length){renderWelcome();return}let day='';for(const m of data){const d=dateLabel(m.created_at);if(d!==day){day=d;const x=document.createElement('div');x.className='day';x.textContent=d;box.appendChild(x)}await appendMessage(m,false)}box.scrollTop=box.scrollHeight}
async function appendMessage(m,scroll=true){const row=document.createElement('div');row.className='message '+(m.sender_id===me.id?'mine':'');let body=m.body?`<div class="bubble">${esc(m.body)}</div>`:'';if(m.attachment_path){const {data}=await client.storage.from('chat-files').createSignedUrl(m.attachment_path,3600);if(data?.signedUrl){const u=esc(data.signedUrl);if((m.attachment_type||'').startsWith('image/'))body+=`<div class="bubble attachment"><img src="${u}" alt="صورة" loading="lazy"></div>`;else if((m.attachment_type||'').startsWith('video/'))body+=`<div class="bubble attachment"><video src="${u}" controls playsinline></video></div>`;else body+=`<div class="bubble"><a class="file-link" href="${u}" target="_blank" rel="noopener">📎 فتح الملف</a></div>`}}row.innerHTML=`${body}<span class="time">${formatTime(m.created_at)}</span>`;$('#messages').appendChild(row);if(scroll)$('#messages').scrollTop=$('#messages').scrollHeight}
async function subscribeMessages(id){if(messageChannel)await client.removeChannel(messageChannel);messageChannel=client.channel('messages:'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},async p=>{if(p.new.sender_id!==me.id)await appendMessage(p.new,true);const c=conversations.find(x=>x.id===id);if(c){c.last=p.new;renderConversationList($('#chatSearch').value)}}).subscribe()}

async function subscribePersonalCalls(){if(personalCallChannel)await client.removeChannel(personalCallChannel);personalCallChannel=client.channel('user-call:'+me.id).on('broadcast',{event:'incoming-call'},p=>{pendingIncoming=p.payload;$('#incomingCaller').textContent=p.payload.callerName||'مكالمة واردة';$('#incomingType').textContent=p.payload.type==='video'?'مكالمة فيديو':'مكالمة صوتية';$('#incomingCall').classList.remove('hidden')}).subscribe()}
async function signalUser(userId,payload){const ch=client.channel('user-call:'+userId);return new Promise(resolve=>{let finished=false;const done=v=>{if(finished)return;finished=true;client.removeChannel(ch);resolve(v)};ch.subscribe(async status=>{if(status==='SUBSCRIBED'){const result=await ch.send({type:'broadcast',event:'incoming-call',payload});done(result)}});setTimeout(()=>done({error:new Error('Call signal timeout')}),7000)})}

async function sendText(text){if(!activeConversation||!text.trim())return;const {error}=await client.from('messages').insert({conversation_id:activeConversation.id,sender_id:me.id,body:text.trim()});if(error)toast(error.message);else $('#messageInput').value=''}
async function sendFile(file){if(!activeConversation)return;if(file.size>20*1024*1024){toast('الملف أكبر من 20MB');return}toast('جارٍ رفع الملف...');const safe=file.name.replace(/[^\w.\-]+/g,'_');const path=`${me.id}/${crypto.randomUUID()}-${safe}`;const {error:up}=await client.storage.from('chat-files').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up){toast(up.message);return}const {error}=await client.from('messages').insert({conversation_id:activeConversation.id,sender_id:me.id,body:'',attachment_path:path,attachment_type:file.type||'application/octet-stream'});if(error){await client.storage.from('chat-files').remove([path]);toast(error.message);return}toast('تم إرسال الملف')}

async function findUser(){const u=$('#userLookup').value.trim().replace(/^@/,'').toLowerCase();if(!u){toast('اكتب اسم المستخدم');return}const {data,error}=await client.from('profiles').select('id,username,display_name').eq('username',u).maybeSingle();const box=$('#lookupResults');box.innerHTML='';if(error){toast(error.message);return}if(!data){box.innerHTML='<p class="lookup-none">لم يتم العثور على المستخدم.</p>';return}if(data.id===me.id){box.innerHTML='<p class="lookup-none">هذا حسابك أنت.</p>';return}const b=document.createElement('button');b.className='lookup-user';b.innerHTML=`<div class="avatar">${esc(initials(data.display_name))}</div><div><b>${esc(data.display_name)}</b><span>@${esc(data.username)}</span></div>`;b.onclick=()=>startConversation(data);box.appendChild(b)}
async function startConversation(user){const {data,error}=await client.rpc('create_direct_conversation',{other_user:user.id});if(error){toast(error.message);return}$('#newChatModal').classList.add('hidden');$('#lookupResults').innerHTML='';$('#userLookup').value='';await loadConversations();const c=conversations.find(x=>x.id===data);if(c)await openConversation(c);else toast('تم إنشاء المحادثة')}
function handleIncomingProfileLink(){const u=new URLSearchParams(location.search).get('user');if(u&&u.toLowerCase()!==(myProfile?.username||'').toLowerCase()){$('#newChatModal').classList.remove('hidden');$('#userLookup').value=u.replace(/^@/,'');setTimeout(()=>$('#lookupBtn').click(),100)}}

async function setupCall(type,other,id,isCaller){currentCall={type,calleeUser:other,conversationId:id,isCaller};$('#callTitle').textContent=`${type==='video'?'مكالمة فيديو':'مكالمة صوتية'} — ${other.display_name}`;$('#callState').textContent=isCaller?'جارٍ الاتصال...':'جاري الانضمام...';$('#callAvatar').textContent=initials(other.display_name);$('#callModal').classList.remove('hidden');$('#localVideo').classList.toggle('hidden',type!=='video');$('#cameraCall').classList.toggle('hidden',type!=='video');$('#remoteVideo').classList.toggle('hidden',type!=='video');try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:type==='video'});$('#localVideo').srcObject=localStream}catch(e){$('#callModal').classList.add('hidden');toast('اسمح للمتصفح باستخدام الميكروفون/الكاميرا');throw e}pc=new RTCPeerConnection(ICE_SERVERS);localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.ontrack=e=>{$('#remoteVideo').srcObject=e.streams[0];$('#callState').textContent='متصل'};pc.onicecandidate=e=>{if(e.candidate)broadcastCall('ice',{candidate:e.candidate})};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState))endCall(false)};await subscribeCallChannel(id);if(isCaller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await broadcastCall('offer',{offer})}}
async function subscribeCallChannel(id){if(callChannel)await client.removeChannel(callChannel);callChannel=client.channel('call-room:'+id).on('broadcast',{event:'offer'},async p=>{if(currentCall?.isCaller)return;await pc.setRemoteDescription(new RTCSessionDescription(p.payload.offer));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await broadcastCall('answer',{answer})}).on('broadcast',{event:'answer'},async p=>{if(currentCall?.isCaller)await pc.setRemoteDescription(new RTCSessionDescription(p.payload.answer))}).on('broadcast',{event:'ice'},async p=>{try{await pc.addIceCandidate(p.payload.candidate)}catch{}}).on('broadcast',{event:'hangup'},()=>endCall(false)).subscribe()}
async function broadcastCall(event,payload){if(callChannel)await callChannel.send({type:'broadcast',event,payload:{...payload,sender:me.id}})}
async function inviteCall(type){if(!activeConversation){toast('اختر محادثة أولاً');return}const other=activeConversation.other;const result=await signalUser(other.id,{conversationId:activeConversation.id,type,callerId:me.id,callerName:myProfile.display_name,calleeId:other.id});if(result?.error){toast('تعذر إرسال طلب المكالمة');return}try{await setupCall(type,other,activeConversation.id,true)}catch{}}
async function acceptIncoming(){if(!pendingIncoming)return;const p=pendingIncoming;pendingIncoming=null;$('#incomingCall').classList.add('hidden');const other={id:p.callerId,display_name:p.callerName,username:''};try{await setupCall(p.type,other,p.conversationId,false)}catch{}}
async function rejectIncoming(){$('#incomingCall').classList.add('hidden');pendingIncoming=null}
async function endCall(send=true){if(send)await broadcastCall('hangup',{});if(pc){pc.close();pc=null}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}if(callChannel){await client.removeChannel(callChannel);callChannel=null}$('#remoteVideo').srcObject=null;$('#localVideo').srcObject=null;$('#callModal').classList.add('hidden');currentCall=null;isMuted=false;cameraOff=false;$('#muteCall').textContent='🎙️';$('#cameraCall').textContent='📷';toast('انتهت المكالمة')}

$('#saveConfig').onclick=()=>{const url=$('#supabaseUrl').value.trim(),key=$('#supabaseKey').value.trim();if(!url||!key){toast('أدخل القيمتين أولاً');return}localStorage.setItem('chat-supabase-url',url);localStorage.setItem('chat-supabase-key',key);location.reload()};
$$('.auth-tabs button').forEach(b=>b.onclick=()=>{$$('.auth-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.auth!=='login');$('#signupForm').classList.toggle('hidden',b.dataset.auth!=='signup');setAuthMessage('')});
$('#loginForm').onsubmit=async e=>{e.preventDefault();setAuthMessage('');const {error}=await client.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)setAuthMessage(error.message)};
$('#signupForm').onsubmit=async e=>{e.preventDefault();setAuthMessage('');const username=$('#signupUsername').value.trim().toLowerCase();if(!/^[a-z0-9_]{3,20}$/.test(username)){setAuthMessage('اسم المستخدم يجب أن يكون 3-20 حرفًا من a-z و0-9 و _.');return}const {error}=await client.auth.signUp({email:$('#signupEmail').value.trim(),password:$('#signupPassword').value,options:{data:{display_name:$('#signupName').value.trim(),username}}});if(error)setAuthMessage(error.message);else setAuthMessage('تم إنشاء الحساب. تحقق من بريدك إذا كان تأكيد البريد مفعّلًا.',true)};
$('#signOutBtn').onclick=async()=>{await endCall(false);await client.auth.signOut();location.reload()};$('#newChatBtn').onclick=()=>{$('#newChatModal').classList.remove('hidden');$('#userLookup').focus()};$('#lookupBtn').onclick=findUser;$('#userLookup').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();findUser()}};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));
$('#composer').onsubmit=async e=>{e.preventDefault();await sendText($('#messageInput').value)};$('#fileBtn').onclick=()=>{if(!activeConversation){toast('اختر محادثة أولاً');return}$('#fileInput').click()};$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(f)await sendFile(f);e.target.value=''};$('#emojiBtn').onclick=()=>$('#emojiPanel').classList.toggle('show');$$('#emojiPanel button').forEach(b=>b.onclick=()=>{$('#messageInput').value+=b.textContent;$('#messageInput').focus()});$('#chatSearch').oninput=e=>renderConversationList(e.target.value);
$('#audioCallBtn').onclick=()=>inviteCall('audio');$('#videoCallBtn').onclick=()=>inviteCall('video');$('#endCall').onclick=()=>endCall(true);$('#endCallTop').onclick=()=>endCall(true);$('#acceptCall').onclick=acceptIncoming;$('#rejectCall').onclick=rejectIncoming;$('#muteCall').onclick=()=>{isMuted=!isMuted;localStream?.getAudioTracks().forEach(t=>t.enabled=!isMuted);$('#muteCall').textContent=isMuted?'🔇':'🎙️'};$('#cameraCall').onclick=()=>{cameraOff=!cameraOff;localStream?.getVideoTracks().forEach(t=>t.enabled=!cameraOff);$('#cameraCall').textContent=cameraOff?'🚫':'📷'};$('#copyShareBtn').onclick=async()=>{await navigator.clipboard.writeText(shareLink(myProfile.username));toast('تم نسخ رابط حسابك')};$('#copyUsernameBtn').onclick=async()=>{await navigator.clipboard.writeText('@'+myProfile.username);toast('تم نسخ المعرف')};$('#blockBtn').onclick=()=>toast('ميزة الحظر تحتاج جدولًا منفصلًا');$('#detailsBtn').onclick=()=>$('#details').classList.toggle('show-mobile');$('#openSidebar').onclick=()=>$('#sidebar').classList.add('open');$('#closeSidebar').onclick=()=>$('#sidebar').classList.remove('open');
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#chatSearch').focus()}if(e.key==='Escape'){$('#emojiPanel').classList.remove('show');$('#newChatModal').classList.add('hidden')}});
boot();
