const FIREBASE_CONFIG = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: ""
};

const state = {
  room: null, user: null, timer: 25 * 60, timerRunning: false, timerInterval: null,
  messages: [], members: [], socialView: 'chats', contacts: [], groups: [], chats: [], selectedChat: null
};
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
function openModal(id){ $(`#${id}`).classList.remove('hidden'); }
function closeModal(id){ $(`#${id}`).classList.add('hidden'); }
function normalizeCode(v){ return v.trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8); }
function makeCode(){ const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join(''); }
function initials(name){ return name.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'S'; }
function timeLabel(date=new Date()){ return date.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); }
function escapeHtml(text=''){ return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function roomStorageKey(code){ return `studcha-room-${code}`; }
function saveRoomLocal(){ if(!state.room) return; localStorage.setItem(roomStorageKey(state.room.code),JSON.stringify({...state.room,members:state.members,messages:state.messages})); }
function loadRoomLocal(code){ try { const x=localStorage.getItem(roomStorageKey(code)); return x?JSON.parse(x):null; } catch { return null; } }
function socialKey(){ return 'studcha-social'; }
function loadSocial(){ try { const x=JSON.parse(localStorage.getItem(socialKey())||'{}'); state.contacts=Array.isArray(x.contacts)?x.contacts:[]; state.groups=Array.isArray(x.groups)?x.groups:[]; state.chats=Array.isArray(x.chats)?x.chats:[]; } catch { state.contacts=[];state.groups=[];state.chats=[]; } }
function saveSocial(){ localStorage.setItem(socialKey(),JSON.stringify({contacts:state.contacts,groups:state.groups,chats:state.chats})); }
function showFormError(target,message=''){ $(target).textContent=message; }
function enterRoom(room,name,isCreator=false){
 state.room=room; state.user={id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,name}; state.messages=Array.isArray(room.messages)?room.messages:[]; state.members=Array.isArray(room.members)?room.members:[];
 if(!state.members.some(m=>m.name===name)) state.members.push({id:state.user.id,name});
 if(isCreator&&!state.messages.length) state.messages.push({system:true,text:`تم إنشاء الغرفة. شارك الكود ${room.code} مع زملائك.`,time:timeLabel()});
 saveRoomLocal(); renderRoom(); loadNotes(); $('#roomView').classList.remove('hidden'); document.body.style.overflow='hidden';
}
function renderRoom(){ if(!state.room)return; $('#roomNameDisplay').textContent=state.room.name; $('#chatTitle').textContent=state.room.name; $('#roomCodeDisplay').textContent=state.room.code; $('#roomAvatar').textContent=initials(state.room.name); $('#memberCount').textContent=state.members.length; $('#membersList').innerHTML=state.members.map(m=>`<div class="member-row"><span class="member-avatar">${escapeHtml(initials(m.name))}</span><span>${escapeHtml(m.name)}${m.id===state.user?.id?' (أنت)':''}</span><i class="member-online"></i></div>`).join(''); $('#chatMessages').innerHTML=state.messages.map(m=>m.system?`<div class="system-message">${escapeHtml(m.text)}</div>`:`<article class="message ${m.userId===state.user?.id?'me':''}"><div class="member-avatar">${escapeHtml(initials(m.userName||'S'))}</div><div class="bubble"><div class="message-author">${escapeHtml(m.userName||'عضو')}</div><p>${escapeHtml(m.text)}</p></div><span class="message-time">${escapeHtml(m.time||'')}</span></article>`).join(''); const chat=$('#chatMessages'); chat.scrollTop=chat.scrollHeight; }
function createRoom(){ const name=$('#roomName').value.trim(), userName=$('#displayName').value.trim(); if(!name)return showFormError('#createError','اكتب اسم الغرفة أولاً.'); if(!userName)return showFormError('#createError','اكتب اسمك.'); const room={code:makeCode(),name,createdAt:Date.now(),members:[],messages:[]}; closeModal('roomModal'); showFormError('#createError'); enterRoom(room,userName,true); history.replaceState({},'',`?room=${room.code}`); navigator.clipboard?.writeText(`${location.origin}${location.pathname}?room=${room.code}`).catch(()=>{}); }
function joinRoom(){ const code=normalizeCode($('#roomCode').value), userName=$('#joinName').value.trim(); if(code.length<6)return showFormError('#joinError','أدخل كودًا من 6 أحرف/أرقام.'); if(!userName)return showFormError('#joinError','اكتب اسمك.'); const room=loadRoomLocal(code); if(!room)return showFormError('#joinError','الغرفة غير موجودة على هذا الجهاز حاليًا.'); closeModal('joinModal'); showFormError('#joinError'); enterRoom(room,userName); history.replaceState({},'',`?room=${room.code}`); }
function sendMessage(text){ if(!state.room||!state.user||!text.trim())return; state.messages.push({userId:state.user.id,userName:state.user.name,text:text.trim(),time:timeLabel()}); saveRoomLocal(); renderRoom(); }
async function copyRoomCode(){ if(!state.room)return; try{await navigator.clipboard.writeText(state.room.code);$('#copyCodeBtn').textContent='تم النسخ ✓';setTimeout(()=>$('#copyCodeBtn').textContent='نسخ',1300);}catch{} }
async function shareRoom(){ if(!state.room)return; const url=`${location.origin}${location.pathname}?room=${state.room.code}`; try{if(navigator.share)await navigator.share({title:`Studcha — ${state.room.name}`,text:'انضم إلى غرفة المذاكرة معي',url});else await navigator.clipboard.writeText(url);}catch{} }
function leaveRoom(){ if(state.room&&state.user){state.members=state.members.filter(m=>m.id!==state.user.id);saveRoomLocal();} state.room=null;state.user=null;$('#roomView').classList.add('hidden');document.body.style.overflow='';history.replaceState({},'',location.pathname); }
function updateTimerDisplay(){ const min=Math.floor(state.timer/60).toString().padStart(2,'0'),sec=(state.timer%60).toString().padStart(2,'0');$('#timerDisplay').textContent=`${min}:${sec}`;$('#timerStartBtn').textContent=state.timerRunning?'إيقاف':'ابدأ'; }
function toggleTimer(){ if(state.timerRunning){clearInterval(state.timerInterval);state.timerRunning=false;}else{state.timerRunning=true;state.timerInterval=setInterval(()=>{state.timer--;if(state.timer<=0){state.timer=0;clearInterval(state.timerInterval);state.timerRunning=false;sendMessage('⏰ انتهت جلسة التركيز! حان وقت الاستراحة.');}updateTimerDisplay();},1000);}updateTimerDisplay(); }
function resetTimer(){clearInterval(state.timerInterval);state.timerRunning=false;state.timer=25*60;updateTimerDisplay();}
function saveNotes(){ if(!state.room)return;localStorage.setItem(`studcha-notes-${state.room.code}`,$('#sessionNotes').value);$('#saveNotesBtn').textContent='تم الحفظ ✓';setTimeout(()=>$('#saveNotesBtn').textContent='حفظ محلي',1200); }
function loadNotes(){ if(state.room)$('#sessionNotes').value=localStorage.getItem(`studcha-notes-${state.room.code}`)||''; }
function contactChatFor(username){ const key=`dm:${username.toLowerCase()}`; let chat=state.chats.find(x=>x.key===key); if(!chat){chat={key,type:'direct',name:username,messages:[]};state.chats.unshift(chat);saveSocial();} return chat; }
function renderSocial(){ const view=state.socialView,container=$('#socialView'); $$('.social-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.socialView===view)); $('#socialViewTitle').textContent=view==='contacts'?'الأصدقاء':view==='groups'?'المجموعات':'المحادثات'; if(view==='contacts'){container.innerHTML=`<div class="social-list">${state.contacts.map(c=>`<button class="social-item" data-open-contact="${escapeHtml(c.username)}"><span class="social-avatar">${escapeHtml(initials(c.name||c.username))}</span><span><strong>${escapeHtml(c.name||c.username)}</strong><small>@${escapeHtml(c.username)}</small></span><b>›</b></button>`).join('')}${!state.contacts.length?'<div class="empty-social">👤 لم تضف أي أصدقاء بعد.</div>':''}</div>`;} else if(view==='groups'){container.innerHTML=`<div class="social-list">${state.groups.map(g=>`<button class="social-item" data-open-group="${escapeHtml(g.id)}"><span class="social-avatar">${escapeHtml(initials(g.name))}</span><span><strong>${escapeHtml(g.name)}</strong><small>${g.members.length} أعضاء</small></span><b>›</b></button>`).join('')}${!state.groups.length?'<div class="empty-social">👥 أنشئ أول مجموعة مذاكرة لك.</div>':''}</div><button class="secondary-btn group-create-btn" id="inlineGroupBtn">+ إنشاء مجموعة</button>`;$('#inlineGroupBtn').onclick=()=>openModal('groupModal');} else {container.innerHTML=`<div class="social-list">${state.chats.map(c=>`<button class="social-item" data-open-chat="${escapeHtml(c.key)}"><span class="social-avatar">${escapeHtml(initials(c.name))}</span><span><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.messages.at(-1)?.text||'ابدأ محادثة جديدة')}</small></span><b>›</b></button>`).join('')}${!state.chats.length?'<div class="empty-social">💬 لا توجد محادثات بعد. أضف صديقًا وابدأ.</div>':''}</div>`;} container.querySelectorAll('[data-open-contact]').forEach(b=>b.onclick=()=>openDirectChat(b.dataset.openContact));container.querySelectorAll('[data-open-chat]').forEach(b=>b.onclick=()=>openSocialChat(b.dataset.openChat));container.querySelectorAll('[data-open-group]').forEach(b=>b.onclick=()=>alert('المجموعة محفوظة محليًا حاليًا. الربط بين الأجهزة يحتاج Backend.')); }
function openDirectChat(username){const chat=contactChatFor(username);openSocialConversation(chat);} function openSocialChat(key){const chat=state.chats.find(x=>x.key===key);if(chat)openSocialConversation(chat);}
function openSocialConversation(chat){ state.selectedChat=chat.key; const conversation=document.createElement('div');conversation.className='social-conversation';conversation.innerHTML=`<div class="conversation-head"><button id="backSocial" class="icon-btn" type="button">→</button><div class="conversation-person"><span class="social-avatar">${escapeHtml(initials(chat.name))}</span><div><strong>${escapeHtml(chat.name)}</strong><small>${chat.type==='group'?'مجموعة مذاكرة':'محادثة خاصة'}</small></div></div><div><button class="tool-btn" type="button">📞</button><button class="tool-btn" type="button">🎥</button></div></div><div class="conversation-messages">${chat.messages.map(m=>`<div class="conversation-bubble ${m.mine?'mine':''}">${escapeHtml(m.text)}<small>${escapeHtml(m.time)}</small></div>`).join('')}</div><form id="conversationForm" class="message-form conversation-form"><input id="conversationInput" maxlength="500" placeholder="اكتب رسالة…" autocomplete="off" /><button type="submit">➤</button></form>`; $('#socialView').innerHTML='';$('#socialView').appendChild(conversation);$('#backSocial').onclick=renderSocial;$('#conversationForm').onsubmit=e=>{e.preventDefault();const input=$('#conversationInput');if(!input.value.trim())return;chat.messages.push({text:input.value.trim(),mine:true,time:timeLabel()});saveSocial();openSocialConversation(chat);}; }
function addContact(){const username=$('#contactInput').value.trim().replace(/^@/,'').replace(/[^a-zA-Z0-9_.-]/g,'');if(username.length<2)return showFormError('#contactError','اكتب اسم مستخدم صحيحًا.');if(state.contacts.some(c=>c.username.toLowerCase()===username.toLowerCase()))return showFormError('#contactError','هذا الصديق موجود بالفعل.');state.contacts.push({username,name:username});saveSocial();closeModal('contactModal');$('#contactInput').value='';showFormError('#contactError');renderSocial();}
function createGroup(){const name=$('#groupName').value.trim();if(!name)return showFormError('#groupError','اكتب اسم المجموعة.');state.groups.push({id:`g-${Date.now()}`,name,members:[{name:'أنت'}],createdAt:Date.now()});saveSocial();closeModal('groupModal');$('#groupName').value='';showFormError('#groupError');state.socialView='groups';renderSocial();}
function setupTheme(){const saved=localStorage.getItem('studcha-theme');if(saved==='dark')document.body.classList.add('dark');$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('studcha-theme',document.body.classList.contains('dark')?'dark':'light');});}
function wireEvents(){ $('#createRoomBtn').onclick=()=>openModal('roomModal');$('#joinRoomBtn').onclick=()=>openModal('joinModal');$('#helpBtn').onclick=()=>openModal('helpModal');$('#createConfirmBtn').onclick=createRoom;$('#joinConfirmBtn').onclick=joinRoom;$('#copyCodeBtn').onclick=copyRoomCode;$('#shareRoomBtn').onclick=shareRoom;$('#leaveRoomBtn').onclick=leaveRoom;$('#timerStartBtn').onclick=toggleTimer;$('#timerResetBtn').onclick=resetTimer;$('#saveNotesBtn').onclick=saveNotes;$('#focusTimerBtn').onclick=()=>$('#timerDisplay').scrollIntoView({behavior:'smooth',block:'center'});$('#messageForm').onsubmit=e=>{e.preventDefault();sendMessage($('#messageInput').value);$('#messageInput').value='';$('#messageInput').focus();};$$('.close-btn').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.add('hidden');});$('#addContactBtn').onclick=()=>openModal('contactModal');$('#newChatBtn').onclick=()=>openModal('contactModal');$('#contactConfirmBtn').onclick=addContact;$('#groupConfirmBtn').onclick=createGroup;$$('.social-nav-btn').forEach(b=>b.onclick=()=>{state.socialView=b.dataset.socialView;renderSocial();});window.addEventListener('beforeunload',()=>{if(state.room)saveRoomLocal();}); }
function bootFromUrl(){const code=new URLSearchParams(location.search).get('room');if(code){$('#roomCode').value=normalizeCode(code);openModal('joinModal');}}
loadSocial();setupTheme();wireEvents();renderSocial();updateTimerDisplay();bootFromUrl();
