-- CHAT: database + RLS + realtime + storage
-- Run this entire file in Supabase SQL Editor.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_]{3,20}$'),
  display_name text not null check (char_length(display_name) between 1 and 30),
  avatar_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id,user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_path text,
  attachment_type text,
  created_at timestamptz not null default now()
);

create index if not exists conversation_members_user_idx on public.conversation_members(user_id);
create index if not exists messages_conversation_idx on public.messages(conversation_id,created_at);

create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists conversations_updated_at on public.conversations;
create trigger conversations_updated_at before update on public.conversations for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
declare
  base text;
  candidate text;
begin
  base := lower(coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email,'user'),'@',1)));
  base := regexp_replace(base,'[^a-z0-9_]','','g');
  if char_length(base) < 3 then base := 'user'||substr(new.id::text,1,6); end if;
  candidate := left(base,20);
  while exists(select 1 from public.profiles where username=candidate) loop
    candidate := left(base,16)||substr(md5(random()::text),1,4);
  end loop;
  insert into public.profiles(id,username,display_name)
  values(new.id,candidate,left(coalesce(new.raw_user_meta_data->>'display_name',candidate),30));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.create_direct_conversation(other_user uuid)
returns uuid
language plpgsql security definer set search_path=public as $$
declare
  existing_id uuid;
  new_id uuid;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if other_user is null or other_user=auth.uid() then raise exception 'Invalid user'; end if;

  select cm1.conversation_id into existing_id
  from public.conversation_members cm1
  join public.conversation_members cm2 on cm2.conversation_id=cm1.conversation_id
  where cm1.user_id=auth.uid() and cm2.user_id=other_user
    and (select count(*) from public.conversation_members x where x.conversation_id=cm1.conversation_id)=2
  limit 1;

  if existing_id is not null then return existing_id; end if;

  insert into public.conversations default values returning id into new_id;
  insert into public.conversation_members(conversation_id,user_id) values(new_id,auth.uid()),(new_id,other_user);
  return new_id;
end; $$;

grant execute on function public.create_direct_conversation(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

drop policy if exists profiles_select_authenticated on public.profiles;
create policy profiles_select_authenticated on public.profiles for select to authenticated using (true);
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists conversations_select_member on public.conversations;
create policy conversations_select_member on public.conversations for select to authenticated using (exists(select 1 from public.conversation_members m where m.conversation_id=id and m.user_id=auth.uid()));
drop policy if exists conversations_insert_authenticated on public.conversations;
create policy conversations_insert_authenticated on public.conversations for insert to authenticated with check (true);

drop policy if exists members_select_member on public.conversation_members;
create policy members_select_member on public.conversation_members for select to authenticated using (exists(select 1 from public.conversation_members mine where mine.conversation_id=conversation_id and mine.user_id=auth.uid()));
drop policy if exists members_insert_self on public.conversation_members;
create policy members_insert_self on public.conversation_members for insert to authenticated with check (user_id=auth.uid());

drop policy if exists messages_select_member on public.messages;
create policy messages_select_member on public.messages for select to authenticated using (exists(select 1 from public.conversation_members m where m.conversation_id=messages.conversation_id and m.user_id=auth.uid()));
drop policy if exists messages_insert_member_sender on public.messages;
create policy messages_insert_member_sender on public.messages for insert to authenticated with check (sender_id=auth.uid() and exists(select 1 from public.conversation_members m where m.conversation_id=messages.conversation_id and m.user_id=auth.uid()));

do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

insert into storage.buckets(id,name,public)
values('chat-files','chat-files',false)
on conflict (id) do nothing;

-- Storage policies: only conversation members can access files whose first folder is their user id.
drop policy if exists chat_files_insert on storage.objects;
create policy chat_files_insert on storage.objects for insert to authenticated with check (bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);

drop policy if exists chat_files_select on storage.objects;
create policy chat_files_select on storage.objects for select to authenticated using (bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);

drop policy if exists chat_files_delete on storage.objects;
create policy chat_files_delete on storage.objects for delete to authenticated using (bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);

-- For simple testing, you can turn off email confirmation in Supabase Auth settings.
